#include <stdio.h>

int main(){
    // Make file pointer
    FILE *ptr;
    // Open and Set write Mode
    ptr = fopen("generate.txt","w");
    // Write text using fprintf()
    fprintf(ptr,"This file is generated by c language");
    // After that close the file
    fclose(ptr);
    return 0;
}